---
abstract: 'Make your Moo-based object constructors blow up on unknown attributes.'
author:
  - 'George Hartzell <hartzell@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Pod::Coverage::TrustPod: '0'
  Test::CPAN::Meta: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
  perl: '5.006'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
  perl: '5.004'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.034, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-StrictConstructor
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Method::Generate::Constructor::Role::StrictConstructor:
    file: lib/Method/Generate/Constructor/Role/StrictConstructor.pm
    version: '0.008'
  MooX::StrictConstructor:
    file: lib/MooX/StrictConstructor.pm
    version: '0.008'
requires:
  B: '0'
  Class::Method::Modifiers: '0'
  Moo: '1.001000'
  Moo::Role: '0'
  bareword::filehandles: '0'
  constant: '0'
  indirect: '0'
  multidimensional: '0'
  perl: '5.006'
  strict: '0'
  strictures: '1'
resources:
  bugtracker: https://github.com/hartzell/moox-strictconstructor/issues
  homepage: https://metacpan.org/release/MooX-StrictConstructor
  repository: git://github.com/hartzell/moox-strictconstructor.git
version: '0.008'
